import { useEffect, useMemo, useState } from "react"
import api from "../services/api"

const competenciaAtual = new Date().toISOString().slice(0,7)
const inicial = { funcionarioId:"", competencia:competenciaAtual, diasTrabalhados:30, horasExtras50:0, horasExtras100:0, faltasDias:0, atrasosHoras:0, comissoes:0, bonus:0, outrosProventos:0, outrosDescontos:0, pensaoAlimenticia:0, descontoValeTransporte:0, descontoValeAlimentacao:0, observacoes:"" }
const moeda = v => Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})

export default function FolhaPagamento() {
  const [clientes,setClientes]=useState([]), [funcionarios,setFuncionarios]=useState([]), [folhas,setFolhas]=useState([])
  const [clienteId,setClienteId]=useState(localStorage.getItem("nexaFolhaClienteId")||localStorage.getItem("nexaFuncionariosClienteId")||"")
  const [competencia,setCompetencia]=useState(competenciaAtual), [form,setForm]=useState(inicial), [previa,setPrevia]=useState(null), [processando,setProcessando]=useState(false)
  useEffect(()=>{ api.get("/clientes").then(r=>setClientes(Array.isArray(r.data)?r.data:[])) },[])
  useEffect(()=>{ if(clienteId){ localStorage.setItem("nexaFolhaClienteId",clienteId); carregar() } else {setFuncionarios([]);setFolhas([])} },[clienteId,competencia])
  async function carregar(){ try { const [f,fp]=await Promise.all([api.get("/funcionarios",{params:{clienteId,status:"Ativo"}}),api.get("/folhas-pagamento",{params:{clienteId,competencia}})]); setFuncionarios(f.data||[]);setFolhas(fp.data||[]) } catch(e){alert(e.response?.data?.message||"Erro ao carregar folha")} }
  function alterar(c,v){setForm(a=>({...a,[c]:v}))}
  async function calcular(){if(!form.funcionarioId)return alert("Selecione o funcionário");setProcessando(true);try{const r=await api.post("/folhas-pagamento/calcular",{...form,competencia});setPrevia(r.data)}catch(e){alert(e.response?.data?.message||"Erro ao calcular")}finally{setProcessando(false)}}
  async function salvar(){if(!previa)await calcular();setProcessando(true);try{await api.post("/folhas-pagamento",{...form,competencia});setPrevia(null);setForm({...inicial,competencia});await carregar()}catch(e){alert(e.response?.data?.message||"Erro ao salvar folha")}finally{setProcessando(false)}}
  async function status(folha,status){try{await api.patch(`/folhas-pagamento/${folha.id}/status`,{status});await carregar()}catch(e){alert(e.response?.data?.message||"Erro ao alterar folha")}}
  async function holerite(folha){try{const r=await api.get(`/folhas-pagamento/${folha.id}/holerite`,{responseType:"blob"});const url=URL.createObjectURL(r.data);const a=document.createElement("a");a.href=url;a.download=`holerite-${folha.competencia}-${folha.funcionario}.pdf`;a.click();URL.revokeObjectURL(url)}catch(e){alert("Erro ao baixar holerite")}}
  const totais=useMemo(()=>folhas.reduce((a,f)=>({bruto:a.bruto+Number(f.totalProventos),descontos:a.descontos+Number(f.totalDescontos),liquido:a.liquido+Number(f.liquido),fgts:a.fgts+Number(f.fgts)}),{bruto:0,descontos:0,liquido:0,fgts:0}),[folhas])
  return <div style={s.page}>
    <div style={s.hero}><div><span style={s.badge}>Pessoas e Folha</span><h2 style={s.h2}>Folha de Pagamento</h2><p style={s.p}>Cálculo mensal e holerite com tabelas oficiais de 2026.</p></div></div>
    <div style={s.filtros}><Campo t="Empresa"><select style={s.input} value={clienteId} onChange={e=>setClienteId(e.target.value)}><option value="">Selecione</option>{clientes.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></Campo><Campo t="Competência"><input type="month" style={s.input} value={competencia} onChange={e=>setCompetencia(e.target.value)}/></Campo></div>
    <div style={s.resumo}>{[["Funcionários",funcionarios.length],["Bruto",moeda(totais.bruto)],["Descontos",moeda(totais.descontos)],["Líquido",moeda(totais.liquido)],["FGTS",moeda(totais.fgts)]].map(([a,b])=><div style={s.stat} key={a}><span>{a}</span><strong>{b}</strong></div>)}</div>
    {clienteId&&<div style={s.card}><h3>Calcular funcionário</h3><div style={s.grid}>
      <Campo t="Funcionário"><select style={s.input} value={form.funcionarioId} onChange={e=>{alterar("funcionarioId",e.target.value);setPrevia(null)}}><option value="">Selecione</option>{funcionarios.map(f=><option key={f.id} value={f.id}>{f.nome} — {f.cargo}</option>)}</select></Campo>
      {[['diasTrabalhados','Dias trabalhados'],['horasExtras50','Horas extras 50%'],['horasExtras100','Horas extras 100%'],['faltasDias','Faltas (dias)'],['atrasosHoras','Atrasos (horas)'],['comissoes','Comissões'],['bonus','Bônus'],['outrosProventos','Outros proventos'],['descontoValeTransporte','Desconto vale-transporte'],['descontoValeAlimentacao','Desconto vale-alimentação'],['pensaoAlimenticia','Pensão alimentícia'],['outrosDescontos','Outros descontos']].map(([c,t])=><Campo key={c} t={t}><input type="number" step="0.01" style={s.input} value={form[c]} onChange={e=>{alterar(c,e.target.value);setPrevia(null)}}/></Campo>)}
    </div><div style={s.actions}><button style={s.secondary} onClick={calcular}>Pré-visualizar</button><button style={s.primary} disabled={processando} onClick={salvar}>Salvar folha</button></div>
    {previa&&<div style={s.preview}><h3>Prévia do cálculo</h3><div style={s.cols}><Itens titulo="Proventos" itens={previa.proventos}/><Itens titulo="Descontos" itens={previa.descontos}/></div><div style={s.totais}><span>INSS {moeda(previa.inss)}</span><span>IRRF {moeda(previa.irrf)}</span><span>FGTS {moeda(previa.fgts)}</span><strong>Líquido {moeda(previa.liquido)}</strong></div></div>}</div>}
    <div style={s.card}><h3>Folhas da competência</h3>{folhas.length===0?<p style={s.p}>Nenhuma folha calculada.</p>:<div style={{overflowX:"auto"}}><table style={s.table}><thead><tr><th>Funcionário</th><th>Bruto</th><th>Descontos</th><th>Líquido</th><th>FGTS</th><th>Status</th><th>Ações</th></tr></thead><tbody>{folhas.map(f=><tr key={f.id}><td><strong>{f.funcionario}</strong></td><td>{moeda(f.totalProventos)}</td><td>{moeda(f.totalDescontos)}</td><td>{moeda(f.liquido)}</td><td>{moeda(f.fgts)}</td><td>{f.status}</td><td><div style={s.actions}><button style={s.small} onClick={()=>holerite(f)}>Holerite PDF</button><button style={f.status==="Fechada"?s.secondary:s.primary} onClick={()=>status(f,f.status==="Fechada"?"Rascunho":"Fechada")}>{f.status==="Fechada"?"Reabrir":"Fechar"}</button></div></td></tr>)}</tbody></table></div>}</div>
    <p style={s.aviso}>Cálculo assistido: confira convenção coletiva, múltiplos vínculos, verbas específicas e dados do eSocial antes do fechamento definitivo.</p>
  </div>
}
function Campo({t,children}){return <label style={s.campo}><span>{t}</span>{children}</label>}
function Itens({titulo,itens=[]}){return <div><strong>{titulo}</strong>{itens.map((i,n)=><div style={s.item} key={n}><span>{i.descricao}</span><b>{moeda(i.valor)}</b></div>)}</div>}
const s={page:{padding:24,minHeight:"100vh",background:"#071d3d",color:"#eef7ff"},hero:{padding:24,borderRadius:18,background:"linear-gradient(135deg,#0b3463,#075b67)",border:"1px solid #147c9c"},badge:{color:"#49f2c2",fontWeight:800},h2:{margin:"6px 0",fontSize:28},p:{color:"#a9c1d8"},filtros:{display:"grid",gridTemplateColumns:"2fr 1fr",gap:14,margin:"18px 0",padding:18,borderRadius:14,background:"#092750"},campo:{display:"flex",flexDirection:"column",gap:6,fontSize:12,color:"#bad0e2"},input:{padding:10,borderRadius:8,border:"1px solid #286589",background:"#0b315d",color:"white"},resumo:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:12,marginBottom:18},stat:{padding:14,borderRadius:12,background:"#092750",display:"flex",flexDirection:"column",gap:8},card:{padding:20,borderRadius:15,background:"#092750",marginBottom:18},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12},actions:{display:"flex",gap:8,justifyContent:"flex-end",alignItems:"center",marginTop:14},primary:{border:0,borderRadius:8,padding:"9px 13px",background:"#20d6a1",color:"#06334a",fontWeight:800,cursor:"pointer"},secondary:{border:"1px solid #34729d",borderRadius:8,padding:"9px 13px",background:"#11375f",color:"white",cursor:"pointer"},small:{border:0,borderRadius:7,padding:"8px",background:"#0aa7c2",color:"white",fontWeight:700,cursor:"pointer"},preview:{marginTop:16,padding:16,borderRadius:12,background:"#061e40"},cols:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:25},item:{display:"flex",justifyContent:"space-between",padding:"7px 0",borderBottom:"1px solid #17466d"},totais:{display:"flex",gap:18,justifyContent:"flex-end",marginTop:15,color:"#bce7dd"},table:{width:"100%",borderCollapse:"collapse"},aviso:{padding:12,borderRadius:8,background:"#3d3316",color:"#ffe29a",fontSize:12}}
