import { useEffect, useMemo, useState } from "react"
import api from "../services/api"
import "./NFe.css"

const hoje = () => new Date().toISOString().slice(0, 10)
const vazio = { codigo: "", descricao: "", codigoTributacaoNacional: "", codigoTributacaoMunicipal: "", itemListaServico: "", cnae: "", aliquotaIss: "", valorUnitario: "", issRetido: false, ativo: true }
const tomadorVazio = { nome: "", cpfCnpj: "", inscricaoMunicipal: "", email: "", cep: "", endereco: "", numero: "", bairro: "", cidade: "", estado: "" }
const dinheiro = (v) => Number(v || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" })

export default function NFSe() {
  const [aba, setAba] = useState("notas"), [clientes, setClientes] = useState([]), [clienteId, setClienteId] = useState("")
  const [config, setConfig] = useState({ serie: "1", proximoNumero: 1, regimeTributario: "", inscricaoMunicipal: "", municipioIbge: "", optanteSimples: true, incentivadorCultural: false })
  const [diagnostico, setDiagnostico] = useState(null), [servicos, setServicos] = useState([]), [servico, setServico] = useState(vazio), [editando, setEditando] = useState(null), [notas, setNotas] = useState([])
  const [tomador, setTomador] = useState(tomadorVazio), [itens, setItens] = useState([]), [competencia, setCompetencia] = useState(hoje()), [deducoes, setDeducoes] = useState(0), [retencoes, setRetencoes] = useState(0), [mensagem, setMensagem] = useState("")

  useEffect(() => { api.get("/clientes").then(({ data }) => { const ativos = (data || []).filter((c) => c.ativo !== false && c.cnpj); setClientes(ativos) }).catch(() => setMensagem("Não foi possível carregar os prestadores.")) }, [])
  useEffect(() => {
    if (clienteId) carregar()
    else {
      setConfig({ serie: "1", proximoNumero: 1, regimeTributario: "", inscricaoMunicipal: "", municipioIbge: "", optanteSimples: true, incentivadorCultural: false })
      setDiagnostico(null); setServicos([]); setNotas([]); setServico(vazio); setEditando(null); setTomador(tomadorVazio); setItens([])
    }
  }, [clienteId])
  async function carregar() { try { const [c, d, s, n] = await Promise.all([api.get(`/nfse/configuracoes/${clienteId}`), api.get(`/nfse/diagnostico/${clienteId}`), api.get(`/nfse/servicos?clienteId=${clienteId}`), api.get(`/nfse/notas?clienteId=${clienteId}`)]); setConfig(c.data); setDiagnostico(d.data); setServicos(s.data || []); setNotas(n.data || []) } catch { setMensagem("Erro ao carregar o módulo de NFS-e.") } }
  async function salvarConfig() { try { await api.put(`/nfse/configuracoes/${clienteId}`, config); setMensagem("Configuração salva em homologação."); await carregar() } catch (e) { setMensagem(e.response?.data?.message || "Erro ao salvar configuração.") } }
  async function salvarServico() { try { const payload = { ...servico, clienteId }; if (editando) await api.put(`/nfse/servicos/${editando}`, payload); else await api.post("/nfse/servicos", payload); setServico(vazio); setEditando(null); setMensagem("Serviço salvo."); await carregar() } catch (e) { setMensagem(e.response?.data?.message || "Erro ao salvar serviço.") } }
  function adicionar(id) { const s = servicos.find((x) => String(x.id) === String(id)); if (s) setItens((a) => [...a, { ...s, servicoId: s.id, quantidade: 1, valorUnitario: Number(s.valorUnitario) }]) }
  const total = useMemo(() => itens.reduce((t, i) => t + Number(i.quantidade || 0) * Number(i.valorUnitario || 0), 0), [itens])
  const iss = useMemo(() => itens.reduce((t, i) => t + Number(i.quantidade || 0) * Number(i.valorUnitario || 0) * Number(i.aliquotaIss || 0) / 100, 0), [itens])
  async function salvarNota() { try { await api.post("/nfse/notas", { clienteId, serie: config.serie, tomador, servicos: itens, competencia, valorDeducoes: deducoes, valorRetencoesFederais: retencoes }); setTomador(tomadorVazio); setItens([]); setDeducoes(0); setRetencoes(0); setMensagem("Rascunho de NFS-e salvo."); await carregar() } catch (e) { setMensagem(e.response?.data?.message || "Erro ao salvar rascunho.") } }

  return <section className="nfe-page">
    <div className="nfe-head"><div><h2>NFS-e de serviços</h2><p>Prestação de serviços · ambiente de homologação</p></div><select value={clienteId} onChange={(e) => setClienteId(e.target.value)}><option value="">Selecione um cliente</option>{clientes.map((c) => <option key={c.id} value={c.id}>{c.nome}</option>)}</select></div>
    <div className="nfe-warning">Transmissão real bloqueada até configurar o Emissor Nacional ou provedor homologado. Inscrição estadual não é necessária.</div>
    {mensagem && <button className="nfe-message" onClick={() => setMensagem("")}>{mensagem} ×</button>}
    <nav className="nfe-tabs">{[["notas","Notas"],["servicos","Serviços"],["config","Configuração"]].map(([id,n]) => <button key={id} className={aba === id ? "active" : ""} onClick={() => setAba(id)}>{n}</button>)}</nav>
    {aba === "config" && <div className="nfe-grid"><div className="nfe-card"><h3>Prestador</h3><label>Ambiente<input value="Homologação" disabled /></label><label>Série<input value={config.serie || "1"} onChange={(e) => setConfig({ ...config, serie: e.target.value })} /></label><label>Próximo número<input type="number" value={config.proximoNumero || 1} onChange={(e) => setConfig({ ...config, proximoNumero: e.target.value })} /></label><label>Regime tributário<select value={config.regimeTributario || ""} onChange={(e) => setConfig({ ...config, regimeTributario: e.target.value })}><option value="">Selecione</option><option value="MEI">MEI</option><option value="Simples Nacional">Simples Nacional</option><option value="Lucro Presumido">Lucro Presumido</option><option value="Lucro Real">Lucro Real</option></select></label><label>Inscrição municipal<input value={config.inscricaoMunicipal || ""} onChange={(e) => setConfig({ ...config, inscricaoMunicipal: e.target.value })} /></label><label>Código IBGE do município<input value={config.municipioIbge || ""} maxLength="7" onChange={(e) => setConfig({ ...config, municipioIbge: e.target.value.replace(/\D/g, "") })} /></label><label><input type="checkbox" checked={config.optanteSimples !== false} onChange={(e) => setConfig({ ...config, optanteSimples: e.target.checked })} /> Optante pelo Simples Nacional</label><label><input type="checkbox" checked={config.incentivadorCultural === true} onChange={(e) => setConfig({ ...config, incentivadorCultural: e.target.checked })} /> Incentivador cultural</label><button className="primary" onClick={salvarConfig}>Salvar configuração</button></div><div className="nfe-card"><h3>Diagnóstico</h3>{diagnostico?.pendencias?.map((p) => <div className="nfe-pendency" key={p}>⚠ {p}</div>)}{diagnostico?.prontoParaRascunho && <div className="nfe-ok">Cadastro pronto para rascunhos.</div>}</div></div>}
    {aba === "servicos" && <><div className="nfe-card nfe-form"><h3>{editando ? "Editar serviço" : "Novo serviço"}</h3>{[["codigo","Código interno"],["descricao","Descrição"],["codigoTributacaoNacional","Código de tributação nacional"],["codigoTributacaoMunicipal","Código municipal"],["itemListaServico","Item da LC 116"],["cnae","CNAE"],["aliquotaIss","Alíquota ISS (%)"],["valorUnitario","Valor padrão"]].map(([c,n]) => <label key={c}>{n}<input type={["aliquotaIss","valorUnitario"].includes(c) ? "number" : "text"} step="0.01" value={servico[c] ?? ""} onChange={(e) => setServico({ ...servico, [c]: e.target.value })} /></label>)}<label><input type="checkbox" checked={servico.issRetido} onChange={(e) => setServico({ ...servico, issRetido: e.target.checked })} /> ISS retido pelo tomador</label><button className="primary" onClick={salvarServico}>Salvar serviço</button></div><div className="nfe-card"><h3>Serviços cadastrados</h3><div className="nfe-table"><table><thead><tr><th>Código</th><th>Descrição</th><th>Tributação</th><th>ISS</th><th>Valor</th><th></th></tr></thead><tbody>{servicos.map((s) => <tr key={s.id}><td>{s.codigo}</td><td>{s.descricao}</td><td>{s.codigoTributacaoNacional || s.codigoTributacaoMunicipal || s.itemListaServico}</td><td>{Number(s.aliquotaIss)}%</td><td>{dinheiro(s.valorUnitario)}</td><td><button onClick={() => { setEditando(s.id); setServico(s); window.scrollTo({ top: 0, behavior: "smooth" }) }}>Editar</button></td></tr>)}</tbody></table></div></div></>}
    {aba === "notas" && <><div className="nfe-card"><h3>Novo rascunho</h3><div className="nfe-form">{[["nome","Nome/Razão social"],["cpfCnpj","CPF/CNPJ"],["inscricaoMunicipal","Inscrição municipal"],["email","E-mail"],["cep","CEP"],["endereco","Endereço"],["numero","Número"],["bairro","Bairro"],["cidade","Cidade"],["estado","UF"]].map(([c,n]) => <label key={c}>{n}<input value={tomador[c]} onChange={(e) => setTomador({ ...tomador, [c]: e.target.value })} /></label>)}<label>Competência<input type="date" value={competencia} onChange={(e) => setCompetencia(e.target.value)} /></label></div><label>Adicionar serviço<select defaultValue="" onChange={(e) => { adicionar(e.target.value); e.target.value = "" }}><option value="">Selecione</option>{servicos.filter((s) => s.ativo).map((s) => <option key={s.id} value={s.id}>{s.codigo} — {s.descricao}</option>)}</select></label>{itens.map((i, idx) => <div className="nfe-item" key={`${i.servicoId}-${idx}`}><strong>{i.descricao}</strong><label>Qtd.<input type="number" value={i.quantidade} onChange={(e) => setItens(itens.map((x,j) => j === idx ? { ...x, quantidade: e.target.value } : x))} /></label><label>Valor<input type="number" value={i.valorUnitario} onChange={(e) => setItens(itens.map((x,j) => j === idx ? { ...x, valorUnitario: e.target.value } : x))} /></label><b>{dinheiro(Number(i.quantidade) * Number(i.valorUnitario))}</b><button onClick={() => setItens(itens.filter((_,j) => j !== idx))}>Remover</button></div>)}<div className="nfe-totals"><label>Deduções<input type="number" value={deducoes} onChange={(e) => setDeducoes(e.target.value)} /></label><label>Retenções federais<input type="number" value={retencoes} onChange={(e) => setRetencoes(e.target.value)} /></label><strong>Serviços: {dinheiro(total)} · ISS: {dinheiro(iss)} · Líquido: {dinheiro(total - Number(retencoes || 0))}</strong></div><button className="primary" onClick={salvarNota}>Salvar rascunho</button><button disabled>Transmitir NFS-e (indisponível)</button></div><div className="nfe-card"><h3>Notas de serviço</h3><div className="nfe-table"><table><thead><tr><th>Data</th><th>Tomador</th><th>Status</th><th>Total</th><th>ISS</th></tr></thead><tbody>{notas.map((n) => <tr key={n.id}><td>{new Date(n.createdAt).toLocaleDateString("pt-BR")}</td><td>{n.tomador?.nome}</td><td><span className="nfe-status">{n.status}</span></td><td>{dinheiro(n.valorServicos)}</td><td>{dinheiro(n.valorIss)}</td></tr>)}</tbody></table></div></div></>}
  </section>
}
