import { useEffect, useMemo, useState } from "react"
import api from "../services/api"
const competenciaAtual=new Date().toISOString().slice(0,7)
const socioInicial={nome:"",cpf:"",dataNascimento:"",nisNitPis:"",qualificacao:"Sócio-administrador",dataEntrada:"",participacaoPercentual:"",valorProLabore:"",dependentesIrrf:0,contribuicaoOutrosVinculos:0,banco:"",agencia:"",conta:"",chavePix:"",status:"Ativo",observacoes:""}
const calculoInicial={socioId:"",valorBruto:"",outrosProventos:0,outrosDescontos:0,pensaoAlimenticia:0,contribuicaoOutrosVinculos:0,dependentesIrrf:0,observacoes:""}
const moeda=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})
export default function ProLabore(){
 const [clientes,setClientes]=useState([]),[socios,setSocios]=useState([]),[itens,setItens]=useState([]),[clienteId,setClienteId]=useState(localStorage.getItem("nexaProLaboreClienteId")||""),[competencia,setCompetencia]=useState(competenciaAtual),[cadastro,setCadastro]=useState(socioInicial),[form,setForm]=useState(calculoInicial),[previa,setPrevia]=useState(null),[editando,setEditando]=useState(null),[ocupado,setOcupado]=useState(false)
 useEffect(()=>{api.get("/clientes").then(r=>setClientes(Array.isArray(r.data)?r.data:[]))},[])
 useEffect(()=>{if(clienteId){localStorage.setItem("nexaProLaboreClienteId",clienteId);carregar()}else{setSocios([]);setItens([])}},[clienteId,competencia])
 async function carregar(){try{const[s,p]=await Promise.all([api.get("/socios",{params:{clienteId,status:"Ativo"}}),api.get("/pro-labore",{params:{clienteId,competencia}})]);setSocios(s.data||[]);setItens(p.data||[])}catch(e){alert(e.response?.data?.message||"Erro ao carregar pró-labore")}}
 const alt=(setter,c,v)=>setter(a=>({...a,[c]:v}))
 async function salvarSocio(){if(!clienteId)return alert("Selecione a empresa");setOcupado(true);try{const body={...cadastro,clienteId};if(editando)await api.put(`/socios/${editando}`,body);else await api.post("/socios",body);setCadastro(socioInicial);setEditando(null);await carregar()}catch(e){alert(e.response?.data?.message||"Erro ao salvar sócio")}finally{setOcupado(false)}}
 function editarSocio(s){setEditando(s.id);setCadastro(Object.fromEntries(Object.keys(socioInicial).map(k=>[k,s[k]??socioInicial[k]])))}
 function selecionarSocio(id){const s=socios.find(x=>String(x.id)===String(id));setForm({...calculoInicial,socioId:id,valorBruto:s?.valorProLabore||"",dependentesIrrf:s?.dependentesIrrf||0,contribuicaoOutrosVinculos:s?.contribuicaoOutrosVinculos||0});setPrevia(null)}
 async function calcular(){if(!form.socioId)return alert("Selecione o sócio");setOcupado(true);try{const r=await api.post("/pro-labore/calcular",{...form,competencia});setPrevia(r.data);return r.data}catch(e){alert(e.response?.data?.message||"Erro ao calcular")}finally{setOcupado(false)}}
 async function salvarCalculo(){if(!form.socioId)return alert("Selecione o sócio");setOcupado(true);try{await api.post("/pro-labore",{...form,competencia});setPrevia(null);setForm(calculoInicial);await carregar()}catch(e){alert(e.response?.data?.message||"Erro ao salvar pró-labore")}finally{setOcupado(false)}}
 async function mudarStatus(item){try{await api.patch(`/pro-labore/${item.id}/status`,{status:item.status==="Fechado"?"Rascunho":"Fechado"});await carregar()}catch(e){alert(e.response?.data?.message||"Erro ao alterar status")}}
 async function recibo(item){try{const r=await api.get(`/pro-labore/${item.id}/recibo`,{responseType:"blob"}),url=URL.createObjectURL(r.data),a=document.createElement("a");a.href=url;a.download=`pro-labore-${item.competencia}-${item.socio}.pdf`;a.click();URL.revokeObjectURL(url)}catch(e){alert("Erro ao baixar recibo")}}
 const totais=useMemo(()=>itens.reduce((a,i)=>({bruto:a.bruto+Number(i.totalProventos),inss:a.inss+Number(i.inss),irrf:a.irrf+Number(i.irrf),liquido:a.liquido+Number(i.liquido)}),{bruto:0,inss:0,irrf:0,liquido:0}),[itens])
 return <div style={s.page}><div style={s.hero}><span style={s.badge}>Sócios e administradores</span><h2 style={s.h2}>Pró-labore</h2><p style={s.p}>Cadastro, cálculo mensal, fechamento e recibo em duas vias.</p></div>
 <div style={s.filtros}><Campo t="Empresa"><select style={s.input} value={clienteId} onChange={e=>setClienteId(e.target.value)}><option value="">Selecione</option>{clientes.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></Campo><Campo t="Competência"><input type="month" style={s.input} value={competencia} onChange={e=>setCompetencia(e.target.value)}/></Campo></div>
 <div style={s.resumo}>{[["Sócios ativos",socios.length],["Bruto",moeda(totais.bruto)],["INSS",moeda(totais.inss)],["IRRF",moeda(totais.irrf)],["Líquido",moeda(totais.liquido)]].map(([r,v])=><div style={s.stat} key={r}><span>{r}</span><strong>{v}</strong></div>)}</div>
 {clienteId&&<><div style={s.card}><h3>{editando?"Editar sócio":"Cadastrar sócio/administrador"}</h3><div style={s.grid}>{[["nome","Nome completo"],["cpf","CPF"],["dataNascimento","Nascimento","date"],["nisNitPis","NIT/PIS"],["qualificacao","Qualificação"],["dataEntrada","Entrada na sociedade","date"],["participacaoPercentual","Participação (%)","number"],["valorProLabore","Pró-labore mensal","number"],["dependentesIrrf","Dependentes IRRF","number"],["contribuicaoOutrosVinculos","INSS retido em outros vínculos","number"],["banco","Banco"],["agencia","Agência"],["conta","Conta"],["chavePix","Chave PIX"]].map(([c,t,tipo="text"])=><Campo key={c} t={t}><input style={s.input} type={tipo} step="0.01" value={cadastro[c]} onChange={e=>alt(setCadastro,c,e.target.value)}/></Campo>)}</div><div style={s.actions}>{editando&&<button style={s.secondary} onClick={()=>{setEditando(null);setCadastro(socioInicial)}}>Cancelar</button>}<button style={s.primary} disabled={ocupado} onClick={salvarSocio}>Salvar sócio</button></div>{socios.length>0&&<div style={s.chips}>{socios.map(x=><button key={x.id} style={s.chip} onClick={()=>editarSocio(x)}>{x.nome} · {moeda(x.valorProLabore)}</button>)}</div>}</div>
 <div style={s.card}><h3>Calcular pró-labore</h3><div style={s.grid}><Campo t="Sócio"><select style={s.input} value={form.socioId} onChange={e=>selecionarSocio(e.target.value)}><option value="">Selecione</option>{socios.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></Campo>{[["valorBruto","Valor bruto"],["outrosProventos","Outros proventos"],["outrosDescontos","Outros descontos"],["pensaoAlimenticia","Pensão alimentícia"],["contribuicaoOutrosVinculos","INSS em outros vínculos"],["dependentesIrrf","Dependentes IRRF"]].map(([c,t])=><Campo key={c} t={t}><input style={s.input} type="number" step="0.01" value={form[c]} onChange={e=>{alt(setForm,c,e.target.value);setPrevia(null)}}/></Campo>)}</div><div style={s.actions}><button style={s.secondary} onClick={calcular}>Pré-visualizar</button><button style={s.primary} disabled={ocupado} onClick={salvarCalculo}>Salvar pró-labore</button></div>{previa&&<div style={s.preview}><strong>Prévia</strong><span>Bruto {moeda(previa.totalProventos)}</span><span>INSS {moeda(previa.inss)}</span><span>IRRF {moeda(previa.irrf)}</span><strong>Líquido {moeda(previa.liquido)}</strong></div>}</div></>}
 <div style={s.card}><h3>Pró-labore da competência</h3>{itens.length===0?<p style={s.p}>Nenhum pró-labore calculado.</p>:<div style={{overflowX:"auto"}}><table style={s.table}><thead><tr><th>Sócio</th><th>Bruto</th><th>INSS</th><th>IRRF</th><th>Líquido</th><th>Status</th><th>Ações</th></tr></thead><tbody>{itens.map(i=><tr key={i.id}><td><strong>{i.socio}</strong></td><td>{moeda(i.totalProventos)}</td><td>{moeda(i.inss)}</td><td>{moeda(i.irrf)}</td><td>{moeda(i.liquido)}</td><td>{i.status}</td><td><div style={s.actions}><button style={s.small} onClick={()=>recibo(i)}>Recibo PDF</button><button style={i.status==="Fechado"?s.secondary:s.primary} onClick={()=>mudarStatus(i)}>{i.status==="Fechado"?"Reabrir":"Fechar"}</button></div></td></tr>)}</tbody></table></div>}</div><p style={s.aviso}>Sem incidência de FGTS. Confira múltiplos vínculos, teto previdenciário e eventos do eSocial antes do fechamento.</p></div>
}
function Campo({t,children}){return <label style={s.campo}><span>{t}</span>{children}</label>}
const s={page:{padding:24,minHeight:"100vh",background:"#071d3d",color:"#eef7ff"},hero:{padding:24,borderRadius:18,background:"linear-gradient(135deg,#0b3463,#075b67)",border:"1px solid #147c9c"},badge:{color:"#49f2c2",fontWeight:800},h2:{margin:"6px 0",fontSize:28},p:{color:"#a9c1d8"},filtros:{display:"grid",gridTemplateColumns:"2fr 1fr",gap:14,margin:"18px 0",padding:18,borderRadius:14,background:"#092750"},campo:{display:"flex",flexDirection:"column",gap:6,fontSize:12,color:"#bad0e2"},input:{padding:10,borderRadius:8,border:"1px solid #286589",background:"#0b315d",color:"white"},resumo:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:12,marginBottom:18},stat:{padding:14,borderRadius:12,background:"#092750",display:"flex",flexDirection:"column",gap:8},card:{padding:20,borderRadius:15,background:"#092750",marginBottom:18},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12},actions:{display:"flex",gap:8,justifyContent:"flex-end",alignItems:"center",marginTop:14},primary:{border:0,borderRadius:8,padding:"9px 13px",background:"#20d6a1",color:"#06334a",fontWeight:800,cursor:"pointer"},secondary:{border:"1px solid #34729d",borderRadius:8,padding:"9px 13px",background:"#11375f",color:"white",cursor:"pointer"},small:{border:0,borderRadius:7,padding:8,background:"#0aa7c2",color:"white",fontWeight:700,cursor:"pointer"},chips:{display:"flex",gap:8,flexWrap:"wrap",marginTop:14},chip:{padding:"8px 10px",borderRadius:20,border:"1px solid #34729d",background:"#0b315d",color:"white",cursor:"pointer"},preview:{display:"flex",gap:20,flexWrap:"wrap",marginTop:16,padding:14,borderRadius:10,background:"#061e40"},table:{width:"100%",borderCollapse:"collapse"},aviso:{padding:12,borderRadius:8,background:"#3d3316",color:"#ffe29a",fontSize:12}}
