const NEXA_VERSION = {
  version: "3.16.0",
  build: "3160",
  release: "Acessos dos clientes",
  date: "08/08/2026",
  status: "Produção",
  frontend: "Vercel",
  backend: "Render",
  banco: "PostgreSQL",
  storage: "Supabase",
  changelog: [
    {
      version: "3.16.0",
      release: "Acessos dos clientes",
      date: "08/08/2026",
      items: ["Status online e último acesso", "Histórico de entradas, visualizações e downloads", "Resumo na Central do Cliente e em Usuários"],
    },
    {
      version: "3.15.2",
      release: "Login inteligente por perfil",
      date: "08/08/2026",
      items: ["Tela única de acesso", "Código exibido automaticamente apenas para usuários do escritório", "Clientes continuam somente com login e senha", "Rodapé público sem descrição interna da atualização"],
    },
    {
      version: "3.15.1",
      release: "Acesso separado para escritório e cliente",
      date: "08/08/2026",
      items: ["Código do escritório removido do acesso dos clientes", "Seleção clara entre acesso do escritório e acesso do cliente", "Código enviado somente no login de administradores e funcionários", "Isolamento multiempresa preservado"],
    },
    {
      version: "3.15.0",
      release: "Arquitetura multiempresa isolada",
      date: "08/08/2026",
      items: ["Isolamento obrigatório por escritório em todas as entidades", "Migração automática dos dados atuais para o escritório principal", "Criação de novos escritórios com administrador e ambiente vazio", "Código do escritório no acesso e administração exclusiva da plataforma"],
    },
    {
      version: "3.14.5",
      release: "Honorários corretos no WhatsApp Inteligente",
      date: "08/08/2026",
      items: ["Modelos financeiros reduzidos a honorários com vencimento e honorários vencidos", "Valor e vencimento obtidos do Financeiro em vez da obrigação fiscal", "Dias de atraso calculados automaticamente"],
    },
    {
      version: "3.14.4",
      release: "Controle compartilhado de mensagens do Nexa Assist WhatsApp",
      date: "08/08/2026",
      items: ["Confirmação de envio antes de retirar a sugestão", "Card enviado removido para todos os colaboradores", "Nova pendência real volta a gerar uma nova sugestão"],
    },
    {
      version: "3.14.3",
      release: "Receita bruta por Bancos e Caixa nos Lançamentos",
      date: "08/08/2026",
      items: ["Vínculo de lançamentos preservado mesmo com diferenças de acentuação no nome do cliente", "Resumo mensal com receita bruta, Bancos, Caixa, despesas e resultado", "Histórico e gráfico contábil exibidos na mesma tela por competência"],
    },
    {
      version: "3.14.2",
      release: "Troca de cliente nos Lançamentos pela Nexa",
      date: "08/08/2026",
      items: ["Filtro de cliente atualizado sem recarregar a página", "Troca direta entre clientes na mesma tela de Lançamentos", "Formulário anterior limpo com segurança ao mudar de cliente"],
    },
    {
      version: "3.14.1",
      release: "DAS-MEI sincronizado com as pendências do escritório",
      date: "07/08/2026",
      items: ["DAS publicado passa a constar no Fiscal interno", "Assistente do Dia reconhece a guia pendente", "Pagamento e edição permanecem sincronizados sem duplicidade"],
    },
    {
      version: "3.14.0",
      release: "Publicação controlada do DAS-MEI no Portal",
      date: "07/08/2026",
      items: ["Seleção das competências por caixa de marcação", "Envio direto das guias selecionadas às Pendências do Portal", "Ações substituídas por edição com registro no histórico"],
    },
    {
      version: "3.13.0",
      release: "DAS-MEI integrado ao Fiscal e Portal",
      date: "07/08/2026",
      items: ["Importação anual movida da Central do Cliente para o Fiscal", "Liberação automática no Portal do Cliente no dia 15", "Visual padronizado com o tema escuro da Nexa"],
    },
    {
      version: "3.12.2",
      release: "Correção visual da tabela DAS-MEI",
      date: "07/08/2026",
      items: ["Cabeçalhos e dados das guias visíveis na Central do Cliente", "Cores e espaçamentos protegidos contra estilos globais"],
    },
    {
      version: "3.12.1",
      release: "DAS-MEI com envio fixo no dia 15",
      date: "07/08/2026",
      items: ["Programação automática para o dia 15 do mês do vencimento", "Remoção da edição manual de data por guia", "Correção da exibição de competência, vencimento e valor"],
    },
    {
      version: "3.12.0",
      release: "DAS-MEI anual programado",
      date: "07/08/2026",
      items: ["Importação em lote dos PDFs mensais do PGMEI", "Leitura automática de CNPJ, competência, vencimento e valor", "Bloqueio de guia consolidada, CNPJ divergente e duplicidade", "Programação e registro do envio pelo WhatsApp"],
    },
    {
      version: "3.11.1",
      release: "Atalho NFS-e Nacional no Portal do Cliente",
      date: "07/08/2026",
      items: ["Acesso direto ao Emissor Nacional da NFS-e", "Portal oficial aberto em nova aba", "Nenhuma credencial gov.br armazenada na Nexa"],
    },
    {
      version: "3.11.0",
      release: "NF-e 4.00 em homologação",
      date: "07/08/2026",
      items: ["XML modelo 55 gerado e assinado com o A1 do cofre", "Autorização síncrona na SEFA/PR em homologação", "Armazenamento do XML autorizado, chave e protocolo", "DANFE de homologação e retorno detalhado das rejeições", "Produção permanece bloqueada"],
    },
    {
      version: "3.10.4",
      release: "Diagnóstico NF-e com a SEFA/PR",
      date: "06/08/2026",
      items: ["NF-e integrada ao certificado A1 do cofre privado", "Teste autenticado do status da SEFA/PR em homologação", "Diagnóstico separado para NF-e modelo 55", "Transmissão mantida bloqueada até a validação do XML assinado"],
    },
    {
      version: "3.10.2",
      release: "Cofre A1 privado para NFS-e",
      date: "06/08/2026",
      items: ["Certificado A1 criptografado antes do armazenamento privado", "Senha protegida separadamente pela API", "Diagnóstico da NFS-e integrado ao A1 ativo", "Homologação mantida sem transmissão prematura"],
    },
    {
      version: "3.10.1",
      release: "Rascunho no padrão visual DANFSe",
      date: "06/08/2026",
      items: ["Modelo A4 inspirado no DANFSe v2.0", "Blocos de DPS, prestador, tomador, serviço, tributação e valores", "Chave e QR Code reservados exclusivamente à nota autorizada"],
    },
    {
      version: "3.10.0",
      release: "Rascunhos inteligentes de NFS-e",
      date: "06/08/2026",
      items: ["Edição, exclusão e impressão de rascunhos", "Validação de CPF, CNPJ, e-mail e UF", "Busca de tomador por CPF/CNPJ e preenchimento por CEP", "Visualização marcada como rascunho sem valor fiscal"],
    },
    {
      version: "3.9.1",
      release: "Numeração correta da DPS",
      date: "05/08/2026",
      items: ["Série e próximo número vinculados à DPS", "Número da NFS-e reservado ao retorno do Emissor Nacional", "Serviços atualizados imediatamente após salvar"],
    },
    {
      version: "3.9.0",
      release: "Base de NFS-e de serviços",
      date: "05/08/2026",
      items: ["Configuração municipal por prestador", "Cadastro fiscal de serviços", "Rascunhos com cálculo de ISS e retenções", "Diagnóstico de prontidão sem exigir inscrição estadual"],
    },
    {
      version: "3.7.0",
      release: "Base de NF-e modelo 55",
      date: "01/08/2026",
      items: [
        "Configuração fiscal do emitente em homologação",
        "Cadastro de produtos fiscais",
        "Rascunhos de NF-e com totais automáticos",
        "Diagnóstico de prontidão para emissão",
      ],
    },
    {
      version: "3.0.1",
      release: "Assistente do Dia",
      date: "09/07/2026",
      items: [
        "Assistente do Dia no Dashboard",
        "Botão Abrir Cliente",
        "Botão WhatsApp com mensagem pronta",
        "Abertura direta da Central do Cliente",
      ],
    },
    {
      version: "3.0.0",
      release: "Central do Cliente",
      date: "08/07/2026",
      items: [
        "Central do Cliente consolidada",
        "Menu lateral por ícones",
        "Cards inteligentes",
        "Resumo financeiro do cliente",
        "Resumo fiscal do cliente",
      ],
    },
    {
      version: "2.2",
      release: "Cards Inteligentes",
      date: "08/07/2026",
      items: [
        "Cards de resumo na Central do Cliente",
        "Histórico e Próximas Ações aprimorados",
        "Documentos e dados cadastrais organizados",
      ],
    },
  ],
}

export default NEXA_VERSION
