const NEXA_VERSION = {
  version: "3.30.0",
  build: "33000",
  release: "Motor Universal Nexa Actions",
  date: "19/08/2026",
  status: "Produção",
  frontend: "Vercel",
  backend: "Render",
  banco: "PostgreSQL",
  storage: "Supabase",
  changelog: [
    { version: "3.30.0", release: "Motor Universal Nexa Actions", date: "19/08/2026", items: ["Mesmo motor para comandos falados e digitados", "Novo cliente cadastrado passo a passo pela Nexa", "Atualização assistida dos dados cadastrais permitidos", "Validação de CPF, telefone, e-mail, CEP, UF e data", "Confirmação final, cancelamento e bloqueio de duplicidade", "Base preparada para conectar os demais módulos"] },
    { version: "3.29.0", release: "Módulo 4 Nexa Assist concluído", date: "19/08/2026", items: ["Ações sensíveis conduzidas passo a passo pela conversa", "Confirmação recuperada mesmo após atualizar a página", "Nenhuma alteração antes dos dados obrigatórios", "Estado aguardando confirmação ou concluído exibido no chat", "Testes automáticos dos fluxos críticos consolidados"] },
    { version: "3.28.12", release: "Médias financeiras no Portal Cliente", date: "19/08/2026", items: ["Média mensal de créditos no Portal Cliente", "Média mensal de débitos no Portal Cliente", "Cálculo sobre todas as competências com movimentação", "Quantidade de meses utilizada apresentada ao cliente"] },
    { version: "3.28.11", release: "Prioridades pagas e carregamento otimizado", date: "19/08/2026", items: ["Guias pagas são removidas das Prioridades do Dia", "Guias pagas não entram no Assistente do Dia", "Removida conferência repetitiva de todos os lançamentos a cada consulta", "Criação integrada permanece automática no momento do pagamento"] },
    { version: "3.28.10", release: "Movimentação e lançamento contábil integrados", date: "18/08/2026", items: ["Pagamento do DAS gera movimento do cliente e lançamento contábil", "Lançamento vinculado à mesma empresa", "Proteção contra registros duplicados", "Movimentos antigos sem lançamento são reparados automaticamente ao consultar"] },
    { version: "3.28.9", release: "Fluxo completo de pendências e DAS", date: "18/08/2026", items: ["Confirmação do pagamento do DAS pela rota correta", "DAS pago sai imediatamente das pendências", "Pagamento gera movimentação da própria empresa sem duplicidade", "Inclui abertura direta da cobrança e prioridade urgente da versão 3.28.8"] },
    { version: "3.28.8", release: "Pendência urgente e abertura direta", date: "18/08/2026", items: ["Prioridade vencida aparece como urgente", "Assistente do Dia abre diretamente a ficha do cliente", "Prioridades do Dia abre diretamente a ficha do cliente", "Cobrança exata é localizada e destacada para conclusão"] },
    { version: "3.28.7", release: "Abertura direta da cobrança do cliente", date: "18/08/2026", items: ["Assistente do Dia abre o cliente mesmo quando a ação não contém ID", "Busca segura pelo nome normalizado", "Cobrança abre diretamente na seção Serviços e cobranças", "ID antigo é removido para impedir abertura do cliente errado"] },
    { version: "3.28.6", release: "Download seguro das guias no Portal Cliente", date: "18/08/2026", items: ["Download do DAS pela rota própria da guia", "Autorização do cliente com identificação normalizada", "PDF do Portal vinculado ao mesmo arquivo disponível no escritório", "Correção da abertura das guias antes do vencimento"] },
    { version: "3.28.2", release: "Pendências somente após o vencimento", date: "17/08/2026", items: ["Tela Pendências Clientes mostra somente guias vencidas", "Guias dentro do prazo permanecem disponíveis apenas no Portal Cliente", "Vencimento passa a ser pendência somente no dia seguinte", "Contadores e lista voltam a usar a mesma regra"] },
    { version: "3.28.1", release: "Guias fiscais visíveis para escritório e cliente", date: "17/08/2026", items: ["DAS a vencer aparece no Portal Cliente", "Guias fiscais reunidas em Pendências Clientes", "Itens a vencer não são tratados como atraso", "DAS sincronizado sem duplicidade"] },
    { version: "3.28.0", release: "Fechamento mensal simplificado", date: "15/08/2026", items: ["Competência mensal na conciliação", "Aviso direto dos movimentos que faltam", "Conclusão do mês em um botão", "Histórico recolhido de meses anteriores", "PDF da conciliação e reabertura pelo administrador"] },
    { version: "3.27.0", release: "Atualização cadastral e gráfico de movimentos", date: "15/08/2026", items: ["Atualização de contato e endereço pelo Portal Cliente", "Proteção de dados fiscais e internos", "Gráfico de receitas e despesas dos últimos seis meses", "Visualização responsiva no computador e celular"] },
    { version: "3.26.0", release: "Classificação e conciliação bancária", date: "15/08/2026", items: ["Classificação individual e em lote", "Sugestões com base no histórico", "Status pendente, classificado, conciliado, ignorado e lançado", "Geração de lançamentos contábeis", "Bloqueio contra lançamento duplicado"] },
    { version: "3.25.1", release: "Atualização imediata dos movimentos bancários", date: "14/08/2026", items: ["Movimentos aparecem imediatamente após importar", "Histórico de importações atualizado sem cache", "Extratos já salvos são recuperados ao abrir a conta"] },
    { version: "3.25.0", release: "Importação de extratos OFX e CSV", date: "14/08/2026", items: ["Upload e leitura de OFX e CSV", "Bloqueio de arquivos e movimentos duplicados", "Resumo de entradas, saídas e saldo líquido", "Movimentos vinculados à conta e à empresa", "Saldo inicial no padrão brasileiro"] },
    { version: "3.24.0", release: "Cadastro de contas para conciliação bancária", date: "14/08/2026", items: ["Conciliação dentro do Contábil", "Várias contas por empresa", "Conta principal, saldo inicial e data-base", "Acesso direto pela ficha do cliente", "Casinha retorna para a empresa selecionada"] },
    { version: "3.23.6", release: "Navegação do cliente e prioridades trabalhistas", date: "14/08/2026", items: ["Casinha em Corrigir Cliente retorna para a ficha da empresa", "Folha vencida em Prioridades do Dia", "Rescisões vencidas ou pagas aguardando finalização", "Itens dentro do prazo continuam fora das pendências"] },
    { version: "3.23.5", release: "Ícone da empresa em todos os módulos", date: "13/08/2026", items: ["Casinha em Funcionários", "Casinha em Folha", "Casinha em Pró-labore", "Casinha em Férias", "Casinha em Rescisão", "Retorno direto à empresa selecionada"] },
    { version: "3.23.4", release: "Retorno completo para a empresa", date: "13/08/2026", items: ["Retorno em Funcionários", "Retorno em Pró-labore", "Retorno em Férias", "Retorno em Folha e Rescisão", "Empresa selecionada preservada"] },
    { version: "3.23.3", release: "Retorno nos módulos de pessoas", date: "13/08/2026", items: ["Botão Voltar para a empresa em Funcionários", "Botão Voltar para a empresa em Pró-labore", "Empresa selecionada preservada no retorno"] },
    { version: "3.23.2", release: "Retorno pela tela de funcionários", date: "13/08/2026", items: ["Botão Voltar para a empresa em Funcionários", "Empresa selecionada preservada no retorno"] },
    { version: "3.23.1", release: "Retorno direto para a empresa", date: "13/08/2026", items: ["Botão Voltar para a empresa na rescisão", "Botão Voltar para a empresa na folha", "Retorno preservando a empresa selecionada"] },
    { version: "3.23.0", release: "Rescisões e folha consolidada", date: "13/08/2026", items: ["Rescisão vinculada ao funcionário e histórico", "PDF vertical em duas vias", "Status calculada, paga e finalizada", "Inativação segura do funcionário ao finalizar", "Processamento, fechamento e resumo PDF da folha por empresa"] },
    { version: "3.22.0", release: "Controle e cálculo de férias", date: "13/08/2026", items: ["Períodos aquisitivo e concessivo", "Cálculo de férias, terço e abono", "Adiantamento da primeira parcela do 13º", "Alertas de férias próximas e vencidas", "Aviso e recibo em PDF"] },
    { version: "3.21.1", release: "DRE profissional em PDF", date: "13/08/2026", items: ["PDF A4 limpo para envio ao cliente", "Empresa e competência selecionadas", "Receitas e despesas por plano de contas", "Resultado e margem gerencial", "Data de emissão e total de lançamentos"] },
    { version: "3.21.0", release: "Calculadora de rescisão trabalhista", date: "13/08/2026", items: ["Cálculo avulso ou por funcionário cadastrado", "Modalidades de desligamento e aviso prévio", "Férias, 13º, INSS, IRRF e FGTS", "Multa rescisória e prazo de pagamento", "Demonstrativo detalhado para PDF"] },
    { version: "3.20.0", release: "Pró-labore e recibo em duas vias", date: "13/08/2026", items: ["Cadastro de sócios por empresa", "Cálculo mensal de INSS e IRRF", "Controle de outros vínculos previdenciários", "Fechamento mensal", "Recibo A4 vertical em duas vias"] },
    { version: "3.19.3", release: "Holerite vertical em duas vias", date: "13/08/2026", items: ["PDF A4 na orientação vertical", "Duas vias no padrão clássico", "Assinatura e data em orientação vertical", "Tabela redimensionada e alinhada"] },
    { version: "3.19.2", release: "Holerite em duas vias", date: "13/08/2026", items: ["Duas vias em uma página", "Percentuais efetivos de INSS e IRRF", "Textos alinhados e nome em destaque", "Área exclusiva para assinatura e data", "Cursor de mão no botão Holerite PDF"] },
    { version: "3.19.1", release: "Holerite no padrão profissional", date: "13/08/2026", items: ["Layout tradicional em verde", "Tabela de vencimentos e descontos", "Bases de INSS, FGTS e IRRF", "Comprovante com assinatura e data"] },
    { version: "3.19.0", release: "Folha de pagamento e holerite", date: "13/08/2026", items: ["Cálculo mensal por funcionário", "INSS e IRRF 2026", "FGTS e salário-família", "Proventos, descontos e fechamento", "Holerite em PDF"] },
    {
      version: "3.18.0",
      release: "Cadastro de funcionários por empresa",
      date: "12/08/2026",
      items: ["Área Pessoas e Folha dentro da empresa", "Cadastro admissional completo", "Dependentes, benefícios e checklist de documentos", "Dados trabalhistas, eSocial, FGTS e pagamento", "Base preparada para folha, holerite e pró-labore"],
    },
    {
      version: "3.17.6",
      release: "Pendências somente após o vencimento",
      date: "12/08/2026",
      items: ["Obrigações em andamento não aparecem como pendência", "Fiscal e cobranças entram um dia após o vencimento", "Iniciar meu dia mostra somente pendências reais", "Solicitações e documentos que exigem ação permanecem visíveis", "Itens duplicados removidos do painel"],
    },
    {
      version: "3.17.5",
      release: "Prioridades vencidas classificadas como críticas",
      date: "12/08/2026",
      items: ["Toda ação vencida força nível urgente", "Pendências consolidadas aparecem em Prioridades do Dia", "Contadores e lista crítica usam a mesma regra"],
    },
    {
      version: "3.17.4",
      release: "Voz sem sobreposição e comandos oficiais aprimorados",
      date: "12/08/2026",
      items: ["Uma nova fala cancela completamente a anterior", "Carteira de Trabalho Digital reforçada no reconhecimento de voz", "Variações naturais de CTPS e carteira digital aceitas"],
    },
    {
      version: "3.17.3",
      release: "Correção de ativações indevidas da voz",
      date: "12/08/2026",
      items: ["Nexa isolado apenas ativa a escuta", "Ativação não consulta automaticamente o cliente anterior", "Palavras curtas sem intenção são descartadas", "Confirmações e nomes em seleções pendentes continuam aceitos"],
    },
    {
      version: "3.17.2",
      release: "Modo de Escuta Protegida",
      date: "12/08/2026",
      items: ["Filtro reforçado contra música, televisão e conversas ao fundo", "Sessão iniciada somente por Nexa, Bom dia ou Boa tarde", "Encerramento automático após 45 segundos sem interação", "Controle para ativar ou desativar a proteção"],
    },
    {
      version: "3.17.1",
      release: "Abertura prioritária de sites oficiais",
      date: "12/08/2026",
      items: ["Comandos de site processados antes da resposta livre", "Link correto da Carteira de Trabalho Digital", "Abertura real preservada mesmo quando o classificador identifica navegação"],
    },
    {
      version: "3.17.0",
      release: "Abertura segura de sites pela Nexa",
      date: "12/08/2026",
      items: ["Abertura direta de portais oficiais", "Carteira de Trabalho Digital, e-CAC, Simples Nacional, PGMEI e NFS-e", "Botão alternativo quando a nova guia for bloqueada", "Validação obrigatória de HTTPS e domínio oficial"],
    },
    {
      version: "3.16.8",
      release: "Inicialização estável da API",
      date: "12/08/2026",
      items: ["Índice do histórico tributário com nome curto e estável", "Reinicialização da API sem colisão de índice", "Correção de roteamento da Andreia preservada"],
    },
    {
      version: "3.16.7",
      release: "Roteamento correto de clientes na Nexa",
      date: "12/08/2026",
      items: ["Correção aplicada também no roteador da API", "Andreia e Andreia Pardo não são confundidas com DRE", "Nomes de clientes têm prioridade correta nos comandos de abertura"],
    },
    {
      version: "3.16.6",
      release: "Reconhecimento seguro de nomes de clientes",
      date: "12/08/2026",
      items: ["Siglas de módulos exigem palavras inteiras", "Andreia não é mais confundida com DRE", "Comandos para abrir clientes seguem para a identificação correta"],
    },
    {
      version: "3.16.5",
      release: "Nexa flutuante e contagem consolidada de atrasos",
      date: "12/08/2026",
      items: ["Painel da Nexa pode ser arrastado livremente", "Posição escolhida preservada entre telas e novos acessos", "Movimento limitado à área visível", "Card Em Atraso alinhado ao Painel Diário"],
    },
    {
      version: "3.16.4",
      release: "Contagem consolidada de ações em atraso",
      date: "12/08/2026",
      items: ["Card Em Atraso alinhado ao Painel Diário da Nexa", "Ações vencidas de todos os módulos contabilizadas sem limitar ao Fiscal"],
    },
    {
      version: "3.16.1",
      release: "Resumo financeiro na Central do Cliente",
      date: "08/08/2026",
      items: ["Movimentos reconhecidos mesmo com diferenças de acentuação no cliente", "Resumo mensal alinhado à tela Movimentos", "Receitas, despesas, saldo e quantidade de lançamentos exibidos na Central"],
    },
    {
      version: "3.16.0",
      release: "Acessos dos clientes",
      date: "08/08/2026",
      items: ["Status online e último acesso", "Histórico de entradas, visualizações e downloads", "Resumo na Central do Cliente e em Usuários"],
    },
    {
      version: "3.15.2",
      release: "Login inteligente por perfil",
      date: "08/08/2026",
      items: ["Tela única de acesso", "Código exibido automaticamente apenas para usuários do escritório", "Clientes continuam somente com login e senha", "Rodapé público sem descrição interna da atualização"],
    },
    {
      version: "3.15.1",
      release: "Acesso separado para escritório e cliente",
      date: "08/08/2026",
      items: ["Código do escritório removido do acesso dos clientes", "Seleção clara entre acesso do escritório e acesso do cliente", "Código enviado somente no login de administradores e funcionários", "Isolamento multiempresa preservado"],
    },
    {
      version: "3.15.0",
      release: "Arquitetura multiempresa isolada",
      date: "08/08/2026",
      items: ["Isolamento obrigatório por escritório em todas as entidades", "Migração automática dos dados atuais para o escritório principal", "Criação de novos escritórios com administrador e ambiente vazio", "Código do escritório no acesso e administração exclusiva da plataforma"],
    },
    {
      version: "3.14.5",
      release: "Honorários corretos no WhatsApp Inteligente",
      date: "08/08/2026",
      items: ["Modelos financeiros reduzidos a honorários com vencimento e honorários vencidos", "Valor e vencimento obtidos do Financeiro em vez da obrigação fiscal", "Dias de atraso calculados automaticamente"],
    },
    {
      version: "3.14.4",
      release: "Controle compartilhado de mensagens do Nexa Assist WhatsApp",
      date: "08/08/2026",
      items: ["Confirmação de envio antes de retirar a sugestão", "Card enviado removido para todos os colaboradores", "Nova pendência real volta a gerar uma nova sugestão"],
    },
    {
      version: "3.14.3",
      release: "Receita bruta por Bancos e Caixa nos Lançamentos",
      date: "08/08/2026",
      items: ["Vínculo de lançamentos preservado mesmo com diferenças de acentuação no nome do cliente", "Resumo mensal com receita bruta, Bancos, Caixa, despesas e resultado", "Histórico e gráfico contábil exibidos na mesma tela por competência"],
    },
    {
      version: "3.14.2",
      release: "Troca de cliente nos Lançamentos pela Nexa",
      date: "08/08/2026",
      items: ["Filtro de cliente atualizado sem recarregar a página", "Troca direta entre clientes na mesma tela de Lançamentos", "Formulário anterior limpo com segurança ao mudar de cliente"],
    },
    {
      version: "3.14.1",
      release: "DAS-MEI sincronizado com as pendências do escritório",
      date: "07/08/2026",
      items: ["DAS publicado passa a constar no Fiscal interno", "Assistente do Dia reconhece a guia pendente", "Pagamento e edição permanecem sincronizados sem duplicidade"],
    },
    {
      version: "3.14.0",
      release: "Publicação controlada do DAS-MEI no Portal",
      date: "07/08/2026",
      items: ["Seleção das competências por caixa de marcação", "Envio direto das guias selecionadas às Pendências do Portal", "Ações substituídas por edição com registro no histórico"],
    },
    {
      version: "3.13.0",
      release: "DAS-MEI integrado ao Fiscal e Portal",
      date: "07/08/2026",
      items: ["Importação anual movida da Central do Cliente para o Fiscal", "Liberação automática no Portal do Cliente no dia 15", "Visual padronizado com o tema escuro da Nexa"],
    },
    {
      version: "3.12.2",
      release: "Correção visual da tabela DAS-MEI",
      date: "07/08/2026",
      items: ["Cabeçalhos e dados das guias visíveis na Central do Cliente", "Cores e espaçamentos protegidos contra estilos globais"],
    },
    {
      version: "3.12.1",
      release: "DAS-MEI com envio fixo no dia 15",
      date: "07/08/2026",
      items: ["Programação automática para o dia 15 do mês do vencimento", "Remoção da edição manual de data por guia", "Correção da exibição de competência, vencimento e valor"],
    },
    {
      version: "3.12.0",
      release: "DAS-MEI anual programado",
      date: "07/08/2026",
      items: ["Importação em lote dos PDFs mensais do PGMEI", "Leitura automática de CNPJ, competência, vencimento e valor", "Bloqueio de guia consolidada, CNPJ divergente e duplicidade", "Programação e registro do envio pelo WhatsApp"],
    },
    {
      version: "3.11.1",
      release: "Atalho NFS-e Nacional no Portal do Cliente",
      date: "07/08/2026",
      items: ["Acesso direto ao Emissor Nacional da NFS-e", "Portal oficial aberto em nova aba", "Nenhuma credencial gov.br armazenada na Nexa"],
    },
    {
      version: "3.11.0",
      release: "NF-e 4.00 em homologação",
      date: "07/08/2026",
      items: ["XML modelo 55 gerado e assinado com o A1 do cofre", "Autorização síncrona na SEFA/PR em homologação", "Armazenamento do XML autorizado, chave e protocolo", "DANFE de homologação e retorno detalhado das rejeições", "Produção permanece bloqueada"],
    },
    {
      version: "3.10.4",
      release: "Diagnóstico NF-e com a SEFA/PR",
      date: "06/08/2026",
      items: ["NF-e integrada ao certificado A1 do cofre privado", "Teste autenticado do status da SEFA/PR em homologação", "Diagnóstico separado para NF-e modelo 55", "Transmissão mantida bloqueada até a validação do XML assinado"],
    },
    {
      version: "3.10.2",
      release: "Cofre A1 privado para NFS-e",
      date: "06/08/2026",
      items: ["Certificado A1 criptografado antes do armazenamento privado", "Senha protegida separadamente pela API", "Diagnóstico da NFS-e integrado ao A1 ativo", "Homologação mantida sem transmissão prematura"],
    },
    {
      version: "3.10.1",
      release: "Rascunho no padrão visual DANFSe",
      date: "06/08/2026",
      items: ["Modelo A4 inspirado no DANFSe v2.0", "Blocos de DPS, prestador, tomador, serviço, tributação e valores", "Chave e QR Code reservados exclusivamente à nota autorizada"],
    },
    {
      version: "3.10.0",
      release: "Rascunhos inteligentes de NFS-e",
      date: "06/08/2026",
      items: ["Edição, exclusão e impressão de rascunhos", "Validação de CPF, CNPJ, e-mail e UF", "Busca de tomador por CPF/CNPJ e preenchimento por CEP", "Visualização marcada como rascunho sem valor fiscal"],
    },
    {
      version: "3.9.1",
      release: "Numeração correta da DPS",
      date: "05/08/2026",
      items: ["Série e próximo número vinculados à DPS", "Número da NFS-e reservado ao retorno do Emissor Nacional", "Serviços atualizados imediatamente após salvar"],
    },
    {
      version: "3.9.0",
      release: "Base de NFS-e de serviços",
      date: "05/08/2026",
      items: ["Configuração municipal por prestador", "Cadastro fiscal de serviços", "Rascunhos com cálculo de ISS e retenções", "Diagnóstico de prontidão sem exigir inscrição estadual"],
    },
    {
      version: "3.7.0",
      release: "Base de NF-e modelo 55",
      date: "01/08/2026",
      items: [
        "Configuração fiscal do emitente em homologação",
        "Cadastro de produtos fiscais",
        "Rascunhos de NF-e com totais automáticos",
        "Diagnóstico de prontidão para emissão",
      ],
    },
    {
      version: "3.0.1",
      release: "Assistente do Dia",
      date: "09/07/2026",
      items: [
        "Assistente do Dia no Dashboard",
        "Botão Abrir Cliente",
        "Botão WhatsApp com mensagem pronta",
        "Abertura direta da Central do Cliente",
      ],
    },
    {
      version: "3.0.0",
      release: "Central do Cliente",
      date: "08/07/2026",
      items: [
        "Central do Cliente consolidada",
        "Menu lateral por ícones",
        "Cards inteligentes",
        "Resumo financeiro do cliente",
        "Resumo fiscal do cliente",
      ],
    },
    {
      version: "2.2",
      release: "Cards Inteligentes",
      date: "08/07/2026",
      items: [
        "Cards de resumo na Central do Cliente",
        "Histórico e Próximas Ações aprimorados",
        "Documentos e dados cadastrais organizados",
      ],
    },
  ],
}

export default NEXA_VERSION
