const NEXA_VERSION = {
  version: "3.40.0",
  build: "33901",
  release: "Ponte segura de diagnóstico",
  date: "22/08/2026",
  status: "Produção",
  frontend: "Vercel",
  backend: "Render",
  banco: "PostgreSQL",
  storage: "Supabase",
  changelog: [
    { version: "3.40.0", release: "Nexa IA principal com contingência", date: "22/08/2026", items: ["OpenAI como inteligência principal", "Groq mantido como reserva automática", "Núcleo de decisão conectado às ferramentas do ERP", "Consultas e correções operacionais com confirmação", "Respostas naturais sem depender de frases fixas", "Nexa exclusiva do Administrador"] },
    { version: "3.39.1", release: "Ponte segura de diagnóstico", date: "22/08/2026", items: ["Nexa Inteligente exclusiva do Administrador", "Novo perfil Empresa sem acesso à Nexa", "Funcionários e clientes sem painel, voz ou rotas da IA", "Pacote automático de diagnóstico para enviar ao ChatGPT", "Incidentes, planos e execuções recentes reunidos em um arquivo", "Credenciais, tokens e segredos removidos automaticamente", "Alterações no banco continuam exigindo confirmação"] },
    { version: "3.39.0", release: "Nexa Intelligence Core", date: "22/08/2026", items: ["Motor agente independente de frases prontas", "Investigação combinada dos módulos do ERP", "Correções operacionais propostas pela IA", "Confirmação obrigatória antes de alterar dados", "Execução em transação com bloqueio concorrente", "Validação automática depois da correção", "Rollback documentado em cada plano", "Valores, exclusões e credenciais continuam bloqueados", "Modelo de IA desacoplado para troca futura de provedor", "Correções de contexto e negação das versões anteriores incluídas"] },
    { version: "3.38.6", release: "Negação segura", date: "22/08/2026", items: ["Comandos negativos não ativam alterações", "Não altere nada mantém a operação em leitura", "Consultas de honorários e movimentos não abrem edição", "Verbos negados deixam de iniciar ações guiadas", "Correções afirmativas continuam disponíveis com confirmação"] },
    { version: "3.38.5", release: "Contexto isolado", date: "22/08/2026", items: ["Pergunta atual tem prioridade sobre o histórico", "Negação de leitura documental respeitada", "Documentos somente quando solicitados", "Resultados documentais antigos isolados do agente", "Consultas ao banco não são desviadas para PDFs anteriores"] },
    { version: "3.38.4", release: "Análise resiliente", date: "21/08/2026", items: ["Contexto do agente reduzido para economizar tokens", "Registros resumidos antes do envio à IA", "Menor risco de limite no plano gratuito da Groq", "Contingência local consulta diretamente o banco", "Análise de cliente funciona mesmo com a IA indisponível", "Aviso vermelho substituído por resposta baseada nos dados", "Solução e próximo passo preservados na contingência"] },
    { version: "3.38.3", release: "Comprovante da análise", date: "21/08/2026", items: ["Resposta declara quais áreas foram verificadas", "Módulos indisponíveis não podem ser omitidos", "Análise incompleta sempre apresenta uma solução", "Registros abertos encontrados são destacados", "Proposta de investigação oferecida quando necessário", "Revisão incorporada à decisão sem chamada adicional", "Menor consumo e maior estabilidade no plano gratuito", "Cobertura confirmada mesmo se a revisão da IA falhar"] },
    { version: "3.38.2", release: "Cobertura completa do cliente", date: "21/08/2026", items: ["Análise geral cruza todos os módulos vinculados", "Conclusão bloqueada quando apenas um módulo foi consultado", "Cadastro, Fiscal, Financeiro, DAS, cobranças e documentos combinados", "Revisão crítica obrigatória antes de responder", "Lacunas e módulos indisponíveis informados claramente", "Solução prática apresentada junto com o problema", "Correção concreta exige explicação e confirmação", "Resposta final permanece curta por padrão", "Isolamento do escritório e campos sensíveis preservados"] },
    { version: "3.38.1", release: "Análise contextual e objetiva", date: "21/08/2026", items: ["Análise de cliente não é mais confundida com avaliação do sistema", "Nome Nexa tratado como chamada da assistente", "Consultas permanecem focadas no cliente solicitado", "Respostas curtas por padrão", "Detalhamento liberado somente quando solicitado", "Análises e comparações permanecem no núcleo agente", "Limite de segurança evita respostas excessivamente longas"] },
    { version: "3.38.0", release: "Núcleo Agente da Nexa", date: "21/08/2026", items: ["Interpretação por objetivo em vez de frases cadastradas", "Planejamento em várias etapas", "Mapa amplo dos módulos e campos autorizados do ERP", "Consultas combinadas entre áreas do banco", "Ferramentas somente de leitura nesta primeira versão", "Ações encaminhadas aos fluxos seguros com confirmação", "Registro auditável de cada execução do agente", "Respostas produzidas no momento conforme os fatos encontrados"] },
    { version: "3.37.3", release: "Linguagem humana e espontânea", date: "21/08/2026", items: ["Modo Desenvolvedor responde como uma colega de equipe", "Termos técnicos traduzidos para linguagem comum", "Respostas curtas e variadas conforme a pergunta", "Detalhes técnicos aparecem somente quando solicitados", "Dados internos deixam de ser despejados na conversa", "Fatos confirmados continuam protegidos contra contradições", "Maior naturalidade sem perder segurança operacional"] },
    { version: "3.37.2", release: "Modo Desenvolvedor Conversacional", date: "21/08/2026", items: ["Resultados técnicos explicados pela IA em linguagem natural", "Histórico e tela atual usados como contexto", "Fatos confirmados continuam controlados pela API", "Número e status do incidente são validados antes da resposta", "Contradições acionam resposta segura automática", "Fallback disponível se o provedor estiver indisponível", "Diagnóstico e conversa funcionam em uma camada híbrida"] },
    { version: "3.37.1", release: "Causa raiz e gestão de incidentes", date: "21/08/2026", items: ["Exceção original registrada na rota de acessos", "Incidentes genéricos atualizados com a causa real", "Classificação temporária, persistente ou em observação", "Encerramento de incidente pela conversa", "Reabertura manual e automática", "Falhas repetidas vinculadas ao mesmo incidente", "Validação e histórico técnico preservados"] },
    { version: "3.37.0", release: "Nexa Modo Desenvolvedor", date: "21/08/2026", items: ["Diagnóstico técnico baseado em incidentes reais", "Verificação de saúde da API e do banco", "Identificador de correlação para rastrear falhas", "Planos de correção vinculados ao incidente", "Etapas, testes e rollback registrados", "Acesso técnico restrito ao administrador", "Nenhuma alteração estrutural é executada sem confirmação"] },
    { version: "3.36.4", release: "Diagnóstico contextual de lançamentos", date: "21/08/2026", items: ["Correção identifica a pendência do cliente aberto", "Resposta informa lançamento, valor, vencimento e status reais", "Ausência de pendência é informada sem resposta genérica", "Múltiplas pendências são listadas para seleção", "Alteração financeira permanece protegida por confirmação"] },
    { version: "3.36.3", release: "Execução operacional durante a visão", date: "21/08/2026", items: ["Navegação e consultas funcionam com a visualização ativa", "Visão acionada somente por pedidos reais de análise da tela", "Consulta exclusiva de clientes inadimplentes", "Mensagem objetiva quando não existem inadimplentes", "Histórico e anotações abertos na seção correta", "Correção de lançamento inicia fluxo guiado em vez de explicação genérica", "Alterações de recebimento continuam exigindo confirmação"] },
    { version: "3.36.2", release: "Compreensão Natural e Correção Contextual", date: "21/08/2026", items: ["Correção segura de digitação em texto e voz", "Interpretação anterior ao roteamento dos comandos", "Frase original preservada no histórico", "Versão corrigida utilizada apenas internamente", "Nomes, documentos, valores e datas protegidos contra correção automática", "Vocabulário adaptativo do escritório e do cliente preservado", "Palavras ambíguas não são alteradas por adivinhação"] },
    { version: "3.36.1", release: "Visão unificada e respostas limpas", date: "21/08/2026", items: ["Visualização disponível também na conversa completa", "Comandos de visão têm prioridade sobre a conversa textual", "Compatibilidade com visualizar e visualise", "Painel flutuante ocultado durante a captura", "JSON interno removido das respostas", "Confirmação sim encerra o compartilhamento", "Abertura limitada às 120 mensagens mais recentes sem apagar o histórico"] },
    { version: "3.36.0", release: "Nexa Analista de Produto", date: "21/08/2026", items: ["Opinião própria sobre o sistema inteiro", "Avaliação organizada em manter, melhorar, acrescentar e remover ou unificar", "Prioridade, impacto e esforço por recomendação", "Análise combina módulos, volumes do ERP e incidentes abertos", "Sugestões registradas para acompanhamento", "Perguntas naturais encaminhadas ao modo Analista de Produto"] },
    { version: "3.35.6", release: "Parecer visual e sugestões de layout", date: "21/08/2026", items: ["Reconhece perguntas como ‘o que achou do layout?’", "Aceita pedidos de opinião, parecer, ideia e sugestão", "Avaliação visual separada de pendências contábeis", "Apresenta ao menos uma melhoria prática para a tela"] },
    { version: "3.35.5", release: "Foco da análise visual", date: "21/08/2026", items: ["Pergunta de esclarecimento para pedidos genéricos", "Análise separada entre cliente, valores e layout", "Visualização permanece ativa enquanto aguarda o foco", "Resposta baseada somente na categoria escolhida"] },
    { version: "3.35.4", release: "Análise visual curta e voz exclusiva", date: "21/08/2026", items: ["Análise visual limitada a três frases", "Somente uma pergunta final sobre desativação", "Voz alternativa bloqueada após início da voz neural", "Respostas objetivas para identificação de erros"] },
    { version: "3.35.3", release: "Confirmação visual direta", date: "21/08/2026", items: ["Confirmação simples ao ativar a visualização", "Análise detalhada somente quando solicitada", "Proteção contra duas vozes reproduzidas ao mesmo tempo", "Resposta inicial curta e objetiva"] },
    { version: "3.35.2", release: "Resposta visual limpa", date: "21/08/2026", items: ["Raciocínio interno do modelo visual não é exibido", "Conteúdo técnico em inglês não é apresentado", "A voz fala somente a resposta final em português", "Versões da API e Web sincronizadas"] },
    { version: "3.35.1", release: "Comandos naturais da Visão Contextual", date: "21/08/2026", items: ["Reconhece ‘consegue visualizar esta tela?’", "Reconhece ‘consegue ver o que estou vendo?’", "Reconhece pedidos naturais com visualizar, analisar, olhar e enxergar", "Ativação encaminhada diretamente ao compartilhamento da tela"] },
    { version: "3.35.0", release: "Nexa Visão Contextual e controle de acesso", date: "21/08/2026", items: ["Visualização da tela ativada por comando de texto ou voz", "Permissão controlada pelo navegador e encerramento por comando", "Análise visual com o modelo multimodal atual da Groq", "Capturas usadas somente durante a análise e não armazenadas", "Bloqueio reversível de usuários sem excluir cadastro ou histórico", "Bloqueio do Portal diretamente pela Central do Cliente", "Alerta de cliente bloqueado com motivo", "Desbloqueio preservando usuários, senhas, documentos e vínculos"] },
    { version: "3.34.0", release: "Nexa Documentos Universais", date: "21/08/2026", items: ["Envio de documentos pelo painel flutuante", "Leitura de PDF, DOCX, TXT, CSV, JSON e XML", "Conteúdo extraído protegido com criptografia autenticada", "Perguntas posteriores sobre o mesmo documento", "Análise disponível no histórico entre computadores", "Cruzamento com cadastro, Fiscal, Financeiro e cobranças do cliente", "Relatório da análise em PDF ou Excel", "Validação do formato real e limite seguro de tamanho"] },
    { version: "3.33.1", release: "Relatórios e sincronização do DAS", date: "21/08/2026", items: ["Relatório geral não herda cliente antigo da conversa", "Daiane e demais clientes com cobranças entram no relatório geral", "Filtro individual somente quando solicitado expressamente", "PDF informa a quantidade de registros", "Conclusão do Fiscal também marca a guia DAS-MEI como paga", "Dashboard não reabre DAS com lançamento contábil confirmado", "Reparo automático dos pagamentos já concluídos", "Bloqueio de lançamento contábil duplicado"] },
    { version: "3.33.0", release: "Nexa Ferramentas Universais", date: "21/08/2026", items: ["Pesquisa atual na internet combinada com dados do ERP", "Relatórios em PDF pela conversa", "Exportação de relatórios para Excel", "Leitura e análise de PDF, DOCX, TXT, CSV, JSON e XML", "Correção conversacional de cobranças com confirmação", "Sincronização transacional entre cobrança e financeiro"] },
    { version: "3.32.2", release: "Conversa única entre dispositivos", date: "21/08/2026", items: ["Conversa ativa definida no PostgreSQL por usuário", "IDs antigos do navegador deixam de separar o histórico", "Notebook e outros computadores retomam a mesma sessão", "Troca de conversa sincronizada pelo servidor", "Painel flutuante sempre consulta a sessão canônica"] },
    { version: "3.32.1", release: "Nexa Dev — Motor de Diagnóstico", date: "21/08/2026", items: ["Conversas sincronizadas entre computadores pela mesma conta", "Conversa mais recente retomada automaticamente", "Painel flutuante conectado ao histórico salvo no servidor", "Incidentes classificados por origem e categoria", "Causa provável, risco, confiança e correção sugerida", "Detalhamento de incidentes diretamente pela conversa da Nexa"] },
    { version: "3.32.0", release: "Nexa Dev — Central de Incidentes", date: "20/08/2026", items: ["Erros da API e do Web capturados automaticamente", "Ocorrências repetidas agrupadas com contexto técnico", "Dados sensíveis removidos antes do registro", "Consulta de incidentes diretamente pela conversa da Nexa", "Autodiagnóstico preventivo do saldo anterior incorporado", "Base preparada para correções testadas, publicação e reversão"] },
    { version: "3.31.4", release: "Cérebro Universal da Nexa", date: "20/08/2026", items: ["Perguntas gerais encaminhadas para resposta por IA", "Respostas amplas para redações, análises, planos, traduções e comparações", "Pesquisa online preservada para informações atuais", "Histórico e anotações abertos diretamente pelo comando", "Anotações internas consultáveis somente pelo escritório", "Mesmo motor de decisão preparado para texto e voz"] },
    { version: "3.31.3", release: "Aviso de instabilidade do sistema", date: "20/08/2026", items: ["Falha de comunicação identificada automaticamente", "Aviso claro para escritório e clientes", "Orientação para não salvar informações durante a falha", "Botão para verificar novamente", "Aviso removido automaticamente após normalização"] },
    { version: "3.31.1", release: "Localização segura de clientes", date: "20/08/2026", items: ["Cliente localizado pelo nome parcial no comando", "Compatibilidade com acentos e nomes compostos", "Correção do filtro que confundia empresa com escritório", "Isolamento multiempresa preservado pelo código do escritório"] },
    { version: "3.31.0", release: "Lançamentos por voz e texto", date: "20/08/2026", items: ["Receitas e despesas registradas pela conversa da Nexa", "Mesmo fluxo para comandos falados e digitados", "Movimento do cliente e lançamento contábil criados juntos", "Resumo e confirmação obrigatória antes de gravar", "Bloqueio de duplicidade recente e isolamento por escritório"] },
    { version: "3.30.0", release: "Motor Universal Nexa Actions", date: "19/08/2026", items: ["Mesmo motor para comandos falados e digitados", "Novo cliente cadastrado passo a passo pela Nexa", "Atualização assistida dos dados cadastrais permitidos", "Validação de CPF, telefone, e-mail, CEP, UF e data", "Confirmação final, cancelamento e bloqueio de duplicidade", "Base preparada para conectar os demais módulos"] },
    { version: "3.29.0", release: "Módulo 4 Nexa Assist concluído", date: "19/08/2026", items: ["Ações sensíveis conduzidas passo a passo pela conversa", "Confirmação recuperada mesmo após atualizar a página", "Nenhuma alteração antes dos dados obrigatórios", "Estado aguardando confirmação ou concluído exibido no chat", "Testes automáticos dos fluxos críticos consolidados"] },
    { version: "3.28.12", release: "Médias financeiras no Portal Cliente", date: "19/08/2026", items: ["Média mensal de créditos no Portal Cliente", "Média mensal de débitos no Portal Cliente", "Cálculo sobre todas as competências com movimentação", "Quantidade de meses utilizada apresentada ao cliente"] },
    { version: "3.28.11", release: "Prioridades pagas e carregamento otimizado", date: "19/08/2026", items: ["Guias pagas são removidas das Prioridades do Dia", "Guias pagas não entram no Assistente do Dia", "Removida conferência repetitiva de todos os lançamentos a cada consulta", "Criação integrada permanece automática no momento do pagamento"] },
    { version: "3.28.10", release: "Movimentação e lançamento contábil integrados", date: "18/08/2026", items: ["Pagamento do DAS gera movimento do cliente e lançamento contábil", "Lançamento vinculado à mesma empresa", "Proteção contra registros duplicados", "Movimentos antigos sem lançamento são reparados automaticamente ao consultar"] },
    { version: "3.28.9", release: "Fluxo completo de pendências e DAS", date: "18/08/2026", items: ["Confirmação do pagamento do DAS pela rota correta", "DAS pago sai imediatamente das pendências", "Pagamento gera movimentação da própria empresa sem duplicidade", "Inclui abertura direta da cobrança e prioridade urgente da versão 3.28.8"] },
    { version: "3.28.8", release: "Pendência urgente e abertura direta", date: "18/08/2026", items: ["Prioridade vencida aparece como urgente", "Assistente do Dia abre diretamente a ficha do cliente", "Prioridades do Dia abre diretamente a ficha do cliente", "Cobrança exata é localizada e destacada para conclusão"] },
    { version: "3.28.7", release: "Abertura direta da cobrança do cliente", date: "18/08/2026", items: ["Assistente do Dia abre o cliente mesmo quando a ação não contém ID", "Busca segura pelo nome normalizado", "Cobrança abre diretamente na seção Serviços e cobranças", "ID antigo é removido para impedir abertura do cliente errado"] },
    { version: "3.28.6", release: "Download seguro das guias no Portal Cliente", date: "18/08/2026", items: ["Download do DAS pela rota própria da guia", "Autorização do cliente com identificação normalizada", "PDF do Portal vinculado ao mesmo arquivo disponível no escritório", "Correção da abertura das guias antes do vencimento"] },
    { version: "3.28.2", release: "Pendências somente após o vencimento", date: "17/08/2026", items: ["Tela Pendências Clientes mostra somente guias vencidas", "Guias dentro do prazo permanecem disponíveis apenas no Portal Cliente", "Vencimento passa a ser pendência somente no dia seguinte", "Contadores e lista voltam a usar a mesma regra"] },
    { version: "3.28.1", release: "Guias fiscais visíveis para escritório e cliente", date: "17/08/2026", items: ["DAS a vencer aparece no Portal Cliente", "Guias fiscais reunidas em Pendências Clientes", "Itens a vencer não são tratados como atraso", "DAS sincronizado sem duplicidade"] },
    { version: "3.28.0", release: "Fechamento mensal simplificado", date: "15/08/2026", items: ["Competência mensal na conciliação", "Aviso direto dos movimentos que faltam", "Conclusão do mês em um botão", "Histórico recolhido de meses anteriores", "PDF da conciliação e reabertura pelo administrador"] },
    { version: "3.27.0", release: "Atualização cadastral e gráfico de movimentos", date: "15/08/2026", items: ["Atualização de contato e endereço pelo Portal Cliente", "Proteção de dados fiscais e internos", "Gráfico de receitas e despesas dos últimos seis meses", "Visualização responsiva no computador e celular"] },
    { version: "3.26.0", release: "Classificação e conciliação bancária", date: "15/08/2026", items: ["Classificação individual e em lote", "Sugestões com base no histórico", "Status pendente, classificado, conciliado, ignorado e lançado", "Geração de lançamentos contábeis", "Bloqueio contra lançamento duplicado"] },
    { version: "3.25.1", release: "Atualização imediata dos movimentos bancários", date: "14/08/2026", items: ["Movimentos aparecem imediatamente após importar", "Histórico de importações atualizado sem cache", "Extratos já salvos são recuperados ao abrir a conta"] },
    { version: "3.25.0", release: "Importação de extratos OFX e CSV", date: "14/08/2026", items: ["Upload e leitura de OFX e CSV", "Bloqueio de arquivos e movimentos duplicados", "Resumo de entradas, saídas e saldo líquido", "Movimentos vinculados à conta e à empresa", "Saldo inicial no padrão brasileiro"] },
    { version: "3.24.0", release: "Cadastro de contas para conciliação bancária", date: "14/08/2026", items: ["Conciliação dentro do Contábil", "Várias contas por empresa", "Conta principal, saldo inicial e data-base", "Acesso direto pela ficha do cliente", "Casinha retorna para a empresa selecionada"] },
    { version: "3.23.6", release: "Navegação do cliente e prioridades trabalhistas", date: "14/08/2026", items: ["Casinha em Corrigir Cliente retorna para a ficha da empresa", "Folha vencida em Prioridades do Dia", "Rescisões vencidas ou pagas aguardando finalização", "Itens dentro do prazo continuam fora das pendências"] },
    { version: "3.23.5", release: "Ícone da empresa em todos os módulos", date: "13/08/2026", items: ["Casinha em Funcionários", "Casinha em Folha", "Casinha em Pró-labore", "Casinha em Férias", "Casinha em Rescisão", "Retorno direto à empresa selecionada"] },
    { version: "3.23.4", release: "Retorno completo para a empresa", date: "13/08/2026", items: ["Retorno em Funcionários", "Retorno em Pró-labore", "Retorno em Férias", "Retorno em Folha e Rescisão", "Empresa selecionada preservada"] },
    { version: "3.23.3", release: "Retorno nos módulos de pessoas", date: "13/08/2026", items: ["Botão Voltar para a empresa em Funcionários", "Botão Voltar para a empresa em Pró-labore", "Empresa selecionada preservada no retorno"] },
    { version: "3.23.2", release: "Retorno pela tela de funcionários", date: "13/08/2026", items: ["Botão Voltar para a empresa em Funcionários", "Empresa selecionada preservada no retorno"] },
    { version: "3.23.1", release: "Retorno direto para a empresa", date: "13/08/2026", items: ["Botão Voltar para a empresa na rescisão", "Botão Voltar para a empresa na folha", "Retorno preservando a empresa selecionada"] },
    { version: "3.23.0", release: "Rescisões e folha consolidada", date: "13/08/2026", items: ["Rescisão vinculada ao funcionário e histórico", "PDF vertical em duas vias", "Status calculada, paga e finalizada", "Inativação segura do funcionário ao finalizar", "Processamento, fechamento e resumo PDF da folha por empresa"] },
    { version: "3.22.0", release: "Controle e cálculo de férias", date: "13/08/2026", items: ["Períodos aquisitivo e concessivo", "Cálculo de férias, terço e abono", "Adiantamento da primeira parcela do 13º", "Alertas de férias próximas e vencidas", "Aviso e recibo em PDF"] },
    { version: "3.21.1", release: "DRE profissional em PDF", date: "13/08/2026", items: ["PDF A4 limpo para envio ao cliente", "Empresa e competência selecionadas", "Receitas e despesas por plano de contas", "Resultado e margem gerencial", "Data de emissão e total de lançamentos"] },
    { version: "3.21.0", release: "Calculadora de rescisão trabalhista", date: "13/08/2026", items: ["Cálculo avulso ou por funcionário cadastrado", "Modalidades de desligamento e aviso prévio", "Férias, 13º, INSS, IRRF e FGTS", "Multa rescisória e prazo de pagamento", "Demonstrativo detalhado para PDF"] },
    { version: "3.20.0", release: "Pró-labore e recibo em duas vias", date: "13/08/2026", items: ["Cadastro de sócios por empresa", "Cálculo mensal de INSS e IRRF", "Controle de outros vínculos previdenciários", "Fechamento mensal", "Recibo A4 vertical em duas vias"] },
    { version: "3.19.3", release: "Holerite vertical em duas vias", date: "13/08/2026", items: ["PDF A4 na orientação vertical", "Duas vias no padrão clássico", "Assinatura e data em orientação vertical", "Tabela redimensionada e alinhada"] },
    { version: "3.19.2", release: "Holerite em duas vias", date: "13/08/2026", items: ["Duas vias em uma página", "Percentuais efetivos de INSS e IRRF", "Textos alinhados e nome em destaque", "Área exclusiva para assinatura e data", "Cursor de mão no botão Holerite PDF"] },
    { version: "3.19.1", release: "Holerite no padrão profissional", date: "13/08/2026", items: ["Layout tradicional em verde", "Tabela de vencimentos e descontos", "Bases de INSS, FGTS e IRRF", "Comprovante com assinatura e data"] },
    { version: "3.19.0", release: "Folha de pagamento e holerite", date: "13/08/2026", items: ["Cálculo mensal por funcionário", "INSS e IRRF 2026", "FGTS e salário-família", "Proventos, descontos e fechamento", "Holerite em PDF"] },
    {
      version: "3.18.0",
      release: "Cadastro de funcionários por empresa",
      date: "12/08/2026",
      items: ["Área Pessoas e Folha dentro da empresa", "Cadastro admissional completo", "Dependentes, benefícios e checklist de documentos", "Dados trabalhistas, eSocial, FGTS e pagamento", "Base preparada para folha, holerite e pró-labore"],
    },
    {
      version: "3.17.6",
      release: "Pendências somente após o vencimento",
      date: "12/08/2026",
      items: ["Obrigações em andamento não aparecem como pendência", "Fiscal e cobranças entram um dia após o vencimento", "Iniciar meu dia mostra somente pendências reais", "Solicitações e documentos que exigem ação permanecem visíveis", "Itens duplicados removidos do painel"],
    },
    {
      version: "3.17.5",
      release: "Prioridades vencidas classificadas como críticas",
      date: "12/08/2026",
      items: ["Toda ação vencida força nível urgente", "Pendências consolidadas aparecem em Prioridades do Dia", "Contadores e lista crítica usam a mesma regra"],
    },
    {
      version: "3.17.4",
      release: "Voz sem sobreposição e comandos oficiais aprimorados",
      date: "12/08/2026",
      items: ["Uma nova fala cancela completamente a anterior", "Carteira de Trabalho Digital reforçada no reconhecimento de voz", "Variações naturais de CTPS e carteira digital aceitas"],
    },
    {
      version: "3.17.3",
      release: "Correção de ativações indevidas da voz",
      date: "12/08/2026",
      items: ["Nexa isolado apenas ativa a escuta", "Ativação não consulta automaticamente o cliente anterior", "Palavras curtas sem intenção são descartadas", "Confirmações e nomes em seleções pendentes continuam aceitos"],
    },
    {
      version: "3.17.2",
      release: "Modo de Escuta Protegida",
      date: "12/08/2026",
      items: ["Filtro reforçado contra música, televisão e conversas ao fundo", "Sessão iniciada somente por Nexa, Bom dia ou Boa tarde", "Encerramento automático após 45 segundos sem interação", "Controle para ativar ou desativar a proteção"],
    },
    {
      version: "3.17.1",
      release: "Abertura prioritária de sites oficiais",
      date: "12/08/2026",
      items: ["Comandos de site processados antes da resposta livre", "Link correto da Carteira de Trabalho Digital", "Abertura real preservada mesmo quando o classificador identifica navegação"],
    },
    {
      version: "3.17.0",
      release: "Abertura segura de sites pela Nexa",
      date: "12/08/2026",
      items: ["Abertura direta de portais oficiais", "Carteira de Trabalho Digital, e-CAC, Simples Nacional, PGMEI e NFS-e", "Botão alternativo quando a nova guia for bloqueada", "Validação obrigatória de HTTPS e domínio oficial"],
    },
    {
      version: "3.16.8",
      release: "Inicialização estável da API",
      date: "12/08/2026",
      items: ["Índice do histórico tributário com nome curto e estável", "Reinicialização da API sem colisão de índice", "Correção de roteamento da Andreia preservada"],
    },
    {
      version: "3.16.7",
      release: "Roteamento correto de clientes na Nexa",
      date: "12/08/2026",
      items: ["Correção aplicada também no roteador da API", "Andreia e Andreia Pardo não são confundidas com DRE", "Nomes de clientes têm prioridade correta nos comandos de abertura"],
    },
    {
      version: "3.16.6",
      release: "Reconhecimento seguro de nomes de clientes",
      date: "12/08/2026",
      items: ["Siglas de módulos exigem palavras inteiras", "Andreia não é mais confundida com DRE", "Comandos para abrir clientes seguem para a identificação correta"],
    },
    {
      version: "3.16.5",
      release: "Nexa flutuante e contagem consolidada de atrasos",
      date: "12/08/2026",
      items: ["Painel da Nexa pode ser arrastado livremente", "Posição escolhida preservada entre telas e novos acessos", "Movimento limitado à área visível", "Card Em Atraso alinhado ao Painel Diário"],
    },
    {
      version: "3.16.4",
      release: "Contagem consolidada de ações em atraso",
      date: "12/08/2026",
      items: ["Card Em Atraso alinhado ao Painel Diário da Nexa", "Ações vencidas de todos os módulos contabilizadas sem limitar ao Fiscal"],
    },
    {
      version: "3.16.1",
      release: "Resumo financeiro na Central do Cliente",
      date: "08/08/2026",
      items: ["Movimentos reconhecidos mesmo com diferenças de acentuação no cliente", "Resumo mensal alinhado à tela Movimentos", "Receitas, despesas, saldo e quantidade de lançamentos exibidos na Central"],
    },
    {
      version: "3.16.0",
      release: "Acessos dos clientes",
      date: "08/08/2026",
      items: ["Status online e último acesso", "Histórico de entradas, visualizações e downloads", "Resumo na Central do Cliente e em Usuários"],
    },
    {
      version: "3.15.2",
      release: "Login inteligente por perfil",
      date: "08/08/2026",
      items: ["Tela única de acesso", "Código exibido automaticamente apenas para usuários do escritório", "Clientes continuam somente com login e senha", "Rodapé público sem descrição interna da atualização"],
    },
    {
      version: "3.15.1",
      release: "Acesso separado para escritório e cliente",
      date: "08/08/2026",
      items: ["Código do escritório removido do acesso dos clientes", "Seleção clara entre acesso do escritório e acesso do cliente", "Código enviado somente no login de administradores e funcionários", "Isolamento multiempresa preservado"],
    },
    {
      version: "3.15.0",
      release: "Arquitetura multiempresa isolada",
      date: "08/08/2026",
      items: ["Isolamento obrigatório por escritório em todas as entidades", "Migração automática dos dados atuais para o escritório principal", "Criação de novos escritórios com administrador e ambiente vazio", "Código do escritório no acesso e administração exclusiva da plataforma"],
    },
    {
      version: "3.14.5",
      release: "Honorários corretos no WhatsApp Inteligente",
      date: "08/08/2026",
      items: ["Modelos financeiros reduzidos a honorários com vencimento e honorários vencidos", "Valor e vencimento obtidos do Financeiro em vez da obrigação fiscal", "Dias de atraso calculados automaticamente"],
    },
    {
      version: "3.14.4",
      release: "Controle compartilhado de mensagens do Nexa Assist WhatsApp",
      date: "08/08/2026",
      items: ["Confirmação de envio antes de retirar a sugestão", "Card enviado removido para todos os colaboradores", "Nova pendência real volta a gerar uma nova sugestão"],
    },
    {
      version: "3.14.3",
      release: "Receita bruta por Bancos e Caixa nos Lançamentos",
      date: "08/08/2026",
      items: ["Vínculo de lançamentos preservado mesmo com diferenças de acentuação no nome do cliente", "Resumo mensal com receita bruta, Bancos, Caixa, despesas e resultado", "Histórico e gráfico contábil exibidos na mesma tela por competência"],
    },
    {
      version: "3.14.2",
      release: "Troca de cliente nos Lançamentos pela Nexa",
      date: "08/08/2026",
      items: ["Filtro de cliente atualizado sem recarregar a página", "Troca direta entre clientes na mesma tela de Lançamentos", "Formulário anterior limpo com segurança ao mudar de cliente"],
    },
    {
      version: "3.14.1",
      release: "DAS-MEI sincronizado com as pendências do escritório",
      date: "07/08/2026",
      items: ["DAS publicado passa a constar no Fiscal interno", "Assistente do Dia reconhece a guia pendente", "Pagamento e edição permanecem sincronizados sem duplicidade"],
    },
    {
      version: "3.14.0",
      release: "Publicação controlada do DAS-MEI no Portal",
      date: "07/08/2026",
      items: ["Seleção das competências por caixa de marcação", "Envio direto das guias selecionadas às Pendências do Portal", "Ações substituídas por edição com registro no histórico"],
    },
    {
      version: "3.13.0",
      release: "DAS-MEI integrado ao Fiscal e Portal",
      date: "07/08/2026",
      items: ["Importação anual movida da Central do Cliente para o Fiscal", "Liberação automática no Portal do Cliente no dia 15", "Visual padronizado com o tema escuro da Nexa"],
    },
    {
      version: "3.12.2",
      release: "Correção visual da tabela DAS-MEI",
      date: "07/08/2026",
      items: ["Cabeçalhos e dados das guias visíveis na Central do Cliente", "Cores e espaçamentos protegidos contra estilos globais"],
    },
    {
      version: "3.12.1",
      release: "DAS-MEI com envio fixo no dia 15",
      date: "07/08/2026",
      items: ["Programação automática para o dia 15 do mês do vencimento", "Remoção da edição manual de data por guia", "Correção da exibição de competência, vencimento e valor"],
    },
    {
      version: "3.12.0",
      release: "DAS-MEI anual programado",
      date: "07/08/2026",
      items: ["Importação em lote dos PDFs mensais do PGMEI", "Leitura automática de CNPJ, competência, vencimento e valor", "Bloqueio de guia consolidada, CNPJ divergente e duplicidade", "Programação e registro do envio pelo WhatsApp"],
    },
    {
      version: "3.11.1",
      release: "Atalho NFS-e Nacional no Portal do Cliente",
      date: "07/08/2026",
      items: ["Acesso direto ao Emissor Nacional da NFS-e", "Portal oficial aberto em nova aba", "Nenhuma credencial gov.br armazenada na Nexa"],
    },
    {
      version: "3.11.0",
      release: "NF-e 4.00 em homologação",
      date: "07/08/2026",
      items: ["XML modelo 55 gerado e assinado com o A1 do cofre", "Autorização síncrona na SEFA/PR em homologação", "Armazenamento do XML autorizado, chave e protocolo", "DANFE de homologação e retorno detalhado das rejeições", "Produção permanece bloqueada"],
    },
    {
      version: "3.10.4",
      release: "Diagnóstico NF-e com a SEFA/PR",
      date: "06/08/2026",
      items: ["NF-e integrada ao certificado A1 do cofre privado", "Teste autenticado do status da SEFA/PR em homologação", "Diagnóstico separado para NF-e modelo 55", "Transmissão mantida bloqueada até a validação do XML assinado"],
    },
    {
      version: "3.10.2",
      release: "Cofre A1 privado para NFS-e",
      date: "06/08/2026",
      items: ["Certificado A1 criptografado antes do armazenamento privado", "Senha protegida separadamente pela API", "Diagnóstico da NFS-e integrado ao A1 ativo", "Homologação mantida sem transmissão prematura"],
    },
    {
      version: "3.10.1",
      release: "Rascunho no padrão visual DANFSe",
      date: "06/08/2026",
      items: ["Modelo A4 inspirado no DANFSe v2.0", "Blocos de DPS, prestador, tomador, serviço, tributação e valores", "Chave e QR Code reservados exclusivamente à nota autorizada"],
    },
    {
      version: "3.10.0",
      release: "Rascunhos inteligentes de NFS-e",
      date: "06/08/2026",
      items: ["Edição, exclusão e impressão de rascunhos", "Validação de CPF, CNPJ, e-mail e UF", "Busca de tomador por CPF/CNPJ e preenchimento por CEP", "Visualização marcada como rascunho sem valor fiscal"],
    },
    {
      version: "3.9.1",
      release: "Numeração correta da DPS",
      date: "05/08/2026",
      items: ["Série e próximo número vinculados à DPS", "Número da NFS-e reservado ao retorno do Emissor Nacional", "Serviços atualizados imediatamente após salvar"],
    },
    {
      version: "3.9.0",
      release: "Base de NFS-e de serviços",
      date: "05/08/2026",
      items: ["Configuração municipal por prestador", "Cadastro fiscal de serviços", "Rascunhos com cálculo de ISS e retenções", "Diagnóstico de prontidão sem exigir inscrição estadual"],
    },
    {
      version: "3.7.0",
      release: "Base de NF-e modelo 55",
      date: "01/08/2026",
      items: [
        "Configuração fiscal do emitente em homologação",
        "Cadastro de produtos fiscais",
        "Rascunhos de NF-e com totais automáticos",
        "Diagnóstico de prontidão para emissão",
      ],
    },
    {
      version: "3.0.1",
      release: "Assistente do Dia",
      date: "09/07/2026",
      items: [
        "Assistente do Dia no Dashboard",
        "Botão Abrir Cliente",
        "Botão WhatsApp com mensagem pronta",
        "Abertura direta da Central do Cliente",
      ],
    },
    {
      version: "3.0.0",
      release: "Central do Cliente",
      date: "08/07/2026",
      items: [
        "Central do Cliente consolidada",
        "Menu lateral por ícones",
        "Cards inteligentes",
        "Resumo financeiro do cliente",
        "Resumo fiscal do cliente",
      ],
    },
    {
      version: "2.2",
      release: "Cards Inteligentes",
      date: "08/07/2026",
      items: [
        "Cards de resumo na Central do Cliente",
        "Histórico e Próximas Ações aprimorados",
        "Documentos e dados cadastrais organizados",
      ],
    },
  ],
}

export default NEXA_VERSION
